<?php if ($this->settings('metatitle')): ?>
   <?php echo $this->headTitle($this->translate($this->settings('metatitle')))->setSeparator(' - ')->setAutoEscape(false) ?>
<?php endif; ?>

<?php foreach ($this->Languagecodes() as $language): ?>
   <?php $this->headLink(array('rel' => 'alternate', 'href' => "http://" . $_SERVER['HTTP_HOST'] . '/' . $language['code'], 'hreflang' => $language['hreflang'])); ?>
<?php endforeach; ?>

<?php $this->headLink(array('rel' => 'alternate', 'href' => "http://" . $_SERVER['HTTP_HOST'], 'hreflang'=> 'x-default')); ?>
<?php $this->headLink(array('rel' => 'alternate', 'href' => "http://" . $_SERVER['HTTP_HOST'] . "/rss.xml", 'type' => 'application/atom+xml', 'title' => 'RSS feed')); ?>
<?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) ?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/application.css?nocache=' . rand(), "all"); ?>
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/application.js'); ?>

<?php echo $this->headLink(); ?>
<?php echo $this->headMeta() ?>

<?php echo $this->settings('headscript')?>
<?php echo $this->settings('ganalytics')?>